// Generated by CoffeeScript 1.6.3
(function() {
  describe("WordScanner", function() {
    it("removes \\r", function() {
      var wscanner;
      wscanner = new WordScanner("Ivan\r\nBilon");
      return expect(wscanner.text).toEqual("Ivan\nBilon");
    });
    describe("next() method", function() {
      var text, wscanner;
      wscanner = null;
      text = "Lorem Ipsum\nDolor";
      beforeEach(function() {
        return wscanner = new WordScanner(text);
      });
      return it("is working correctly", function() {
        expect(wscanner.next()).toEqual("Lorem");
        expect(wscanner.next()).toEqual(" ");
        expect(wscanner.next()).toEqual("Ipsum");
        expect(wscanner.next()).toEqual("\n");
        expect(wscanner.next()).toEqual("Dolor");
        return expect(wscanner.next()).toEqual(null);
      });
    });
    return describe("hasNext() method", function() {
      var wscanner;
      wscanner = null;
      beforeEach(function() {
        return wscanner = new WordScanner("ivan bilon");
      });
      return it("is working fine", function() {
        expect(wscanner.hasNext()).toBeTruthy();
        wscanner.next();
        expect(wscanner.hasNext()).toBeTruthy();
        wscanner.next();
        expect(wscanner.hasNext()).toBeTruthy();
        wscanner.next();
        return expect(wscanner.hasNext()).toBeFalsy();
      });
    });
  });

}).call(this);
