// Generated by CoffeeScript 1.6.3
(function() {
  window.WordScanner = (function() {
    function WordScanner(text) {
      this.text = text.replace("\r", "");
      this.curPos = 0;
    }

    WordScanner.prototype.next = function() {
      var letter, nextLetter, word;
      if (this.curPos == null) {
        return null;
      }
      word = "";
      letter = "";
      nextLetter = "";
      while (true) {
        letter = this.text[this.curPos];
        word += letter;
        if (this.curPos === this.text.length - 1) {
          this.curPos = null;
          break;
        } else {
          this.curPos++;
        }
        if (letter === " " || letter === "\n") {
          break;
        }
        nextLetter = this.text[this.curPos];
        if (nextLetter === " " || nextLetter === "\n") {
          break;
        }
      }
      return word;
    };

    WordScanner.prototype.hasNext = function() {
      if (this.curPos !== null) {
        return true;
      } else {
        return false;
      }
    };

    return WordScanner;

  })();

}).call(this);
